home_space/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('homehelp', views.hh_index, name='hh_index'),
    path('dashboard',views.dashboard,name='dashboard'),

    #SPACE PAGES
    path('new_home', views.new_home, name='new_home'),
    path('<home_id>/new_room', views.new_room, name='new_room'),
    path('<room_id>/edit', views.edit_room, name='edit_room'),
    path('room/<room_id>', views.room, name='room'),
    path('room/<room_id>/delete', views.delete_room, name='delete_room'),
    path('room/<room_id>/add_inventory', views.new_inventory, name='new_inventory'),

    path('inventory/<inventory_id>', views.inventory, name='inventory'),

    path('new_garage_sale', views.new_garage_sale, name='new_garage_sale'),
    path('garage_sales', views.garage_sales, name='garage_sales'),
    path('garage_sale/<sale_id>', views.garage_sale, name='garage_sale'),
    path('edit_sale/<sale_id>', views.edit_sale, name='edit_sale'),
    path('garage_sale/<sale_id>/<item_id>', views.add_item, name='add_item'),

    path('<inventory_id>/new_item',views.new_item,name='new_item'),
    path('edit_item/<item>',views.edit_item,name='edit_item'),
    path('<item>/delete',views.delete_item,name='delete_item'),

    path('item/<item_id>', views.item, name='item'),
    path('item/<item_id>/new_item_image', views.new_item_image, name='new_item_image'),

    path('item_results', views.get_items, name='item_results'),

    #FOOD
    path('<inventory_id>/new_food',views.new_food,name='new_food'),
    path('edit/<food>',views.edit_food ,name='edit_food'),

    #RECIPES
    path('recipes',views.recipes, name='recipes'),
    path('recipes/<recipe>',views.recipe,name='recipe'),
    path('new_recipe',views.new_recipe, name='new_recipe'),

    #INGREDIENTS
    path('new_ingredient',views.new_ingredient,name='new_ingredient'),

    #ABOUT
    path('about_homehelp',views.about_hh,name='about_hh'),
]

home_space/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
import django.utils

HELP_TEXT = {
	'ITEM': {
		'info':'A short description. Is adjustable.',
		'quantity':'Is adjustable.',
		'bot_date':'',
	},
	
	'FOOD': {
		'bot_date':'',
		'exp_date':'',
		'consumed':''
	},
	
	'SPACE': {
		'super_space':'',
		'kind':''
	},
}

FOOD_STORAGE_IND = [
	'Kitchen',
	'Freezer',
	'Pantry',
]


def user_directory_path(instance, filename):
	try:
		return '{0}/{1}/{2}'.format('items', instance.item.name, filename)
	except AttributeError:
		print("Attribute Error: user_directory_path 1")
		pass

class Space(models.Model):
	name = models.CharField(max_length=35)

	def __str__(self):
		return self.name

	class Meta:
		abstract = True

class Home(Space):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = 'homes'

class Membership(models.Model):
	household = models.ForeignKey(Home, on_delete=models.CASCADE)
	member = models.ForeignKey(User, on_delete=models.CASCADE)
	can_edit = models.BooleanField(default=True)

class Room(Space):
	home = models.ForeignKey(Home, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = 'rooms'

class Inventory(Space):
	holds_food = models.BooleanField(default=False)
	space = models.ForeignKey(Room, on_delete=models.CASCADE)

'''Food and Non-food items share some similar descriptive qualities of which are
present below. 
'''
class Info(models.Model):
	space = models.ForeignKey(Inventory, on_delete=models.CASCADE)
	#Date bought and/or put into inventory. 
	bot_date = models.DateField(help_text=HELP_TEXT['ITEM']['bot_date'])

	class Meta:
		abstract=True

class ItemInfo(models.Model):
	name = models.CharField(max_length=80)

	class Meta:
		abstract = True

	def __str__(self):
		return self.name

class FoodInfo(ItemInfo):
	NUMBER = 'n'
	GRAM = 'gm'
	OUNCES = 'oz'
	POUNDS = 'lb'
	FLUIDOUNCES = 'floz'
	TABLESPOON = 'tbsp'
	LITER = 'L'
	GALLON = 'gal'
	CUP = 'c'
	PINT = 'pt'
	MILLILITER = 'mL'
	TEASPOON = 'tsp'

	METRIC = [
		(NUMBER, 'number'),
		(GRAM,'gram'),
		(OUNCES,'ounces'),
		(POUNDS,'pounds'),
		(FLUIDOUNCES,'fluid ounces'),
		(TABLESPOON,'tablespoon'),
		(LITER,'liter'),
		(GALLON,'gallon'),
		(CUP,'cup'),
		(PINT,'pint'),
		(MILLILITER,'milliliter'),
		(TEASPOON,'teaspoon'),
	]

	quantity = models.DecimalField(default=1, max_digits=6, decimal_places=3, help_text=HELP_TEXT['ITEM']['quantity'])
	metric = models.CharField(max_length=4,choices=METRIC, blank=True, default=METRIC[0])

	class Meta:
		abstract = True

'''For now weight and '''
class Item(Info, ItemInfo):
	info = models.CharField(max_length=100, blank=True, help_text=HELP_TEXT['ITEM']['info'])
	quantity = models.IntegerField(default=1,help_text=HELP_TEXT['ITEM']['quantity'])

	class Meta:
		verbose_name_plural = 'items'

class ItemImage(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	image = models.ImageField(upload_to=user_directory_path, blank=True, null=True)

class Recipe(models.Model):
	name = models.CharField(max_length=50)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = 'Recipes'

class Step(models.Model):
	recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
	step_number = models.IntegerField()
	instruction = models.TextField()

	class Meta:
		verbose_name_plural = 'steps'

class Ingredient(FoodInfo):
	recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

	class Meta:
		verbose_name_plural = 'ingredients'

class Food(FoodInfo, Info):
	exp_date = models.DateField(help_text=HELP_TEXT['FOOD']['exp_date'])
	consumed = models.BooleanField(default=False,help_text=HELP_TEXT['FOOD']['consumed'])

class FoodImage(models.Model):
	item = models.ForeignKey(Food, on_delete=models.CASCADE)
	image = models.ImageField(upload_to=user_directory_path, blank=True,  null=True)

class GarageSale(models.Model):
	name = models.CharField(max_length=50)
	start_date = models.DateField(blank=True, null=True)
	end_date = models.DateField(blank=True, null=True)
	home = models.ForeignKey(Home, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

class ForSale(models.Model):
	vendor = models.ForeignKey(GarageSale, on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)

home_space/templates/home_space/dashboard.html
{% extends "home_space/base.html" %}
{% load bootstrap4 %}
{% block title %}Dashboard{% endblock %}
{% block content %}
{% if homes %}
	{% for home in homes %}
	<div class='pb-3 d-inline mb-2'>
		<h2 class='d-inline'><i class="glyphicon glyphicon-home"></i> {{ home }}</h2>
		<h5>Owner: {{ home.owner }} - Members: {% for member in home.membership_set.all %}{{ member.member }}{% endfor %}</h5>
	</div>
	<div class="btn-group">
		<div>
			<a href="#" class='btn btn-dark dropdown-toggle' id='{{home.id}}_add_room_dd' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-plus-sign"></i> Room</a>
			<div class="dropdown float-left">
				<div class='dropdown-menu p-2' aria-labelledby="{{home.id}}_add_room_dd">
					<form action="{% url 'new_room' home.id %}" method='post'>
						{% csrf_token %}
						{% bootstrap_form room_form %}
						<button name="submit" class="btn btn-dark mt-0">Add Room</button>
					</form>
				</div>
			</div>
			<a href="{% url 'new_garage_sale' %}" class='btn btn-dark'>Garage Sale +</a>
		</div>
	</div>
	<div>
		<div class='rooms d-flex row mt-4'>
		{% for room in home.room_set.all %}
			{% include 'home_space/room_tile.html' %}
		{% empty %}
			<p>There is nothing here.</p>
			<hr>
		{% endfor %}
		</div>
	</div>
	{% endfor %}
{% else %}
	<h3>There is no home setup yet. Add one here</h3>
	<div>
		<form action="{% url 'new_home' %}" method='post'>
			{% csrf_token %}
			{% bootstrap_form home_form %}
			<button name="submit">Add Home</button>
		</form>
	</div>
{% endif %}
{% endblock %}

home_space/templates/home_space/edit_food.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block content %}
<div>
	<h3>Edit {{ food }}</h3>
	<form action="{% url 'edit_food' food.id %}" method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		<button name="submit">Update</button>
	</form>
</div>
{% endblock %}

home_space/templates/home_space/edit_item.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block title %}Edit {{item}}{% endblock %}
{% block content %}
<div>
	<h3 class="mt-0">Edit {{ item }}</h3>
	<form action="{% url 'edit_item' item.id %}" method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		<button class="btn btn-dark" name="submit">Update</button>
		<a class="btn btn-dark" href="{% url 'delete_item' item.id %}">Delete</a>
	</form>
	{% if item.itemimage_set.all.count > 0 %}
	<h3>Images</h3>
	{% endif %}
	<div class="d-flex row">
	{% for image in item.itemimage_set.all %}
		<div class="col-3">
			<a href=""><img src="{{ image.image.url }}" width="100%"></a>
		</div>
	{% endfor %}
	</div>
</div>
{% endblock %}

home_space/templates/home_space/edit_room.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block title %}Edit {{room}}{% endblock %}
{% block content %}
<div>
	<h3>Edit {{ room }}</h3>
	<form action="{% url 'edit_room' room.id %}" method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% for field in i_form %}
			<div>
				<b class="mr-1">{{field.label}}</b>
				{{ field }}
			</div>
		{% endfor %}
		<button name="submit" class='btn btn-dark'>Update</button>
	</form>
</div>
{% endblock %}

home_space/templates/home_space/edit_sale.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block title %}Edit {{sale}}{% endblock %}
{% block content %}
<div>
    <h2 class="mt-0">Edit {{ sale }}</h2>
    <form action="{% url 'edit_sale' sale.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class='btn btn-dark' name='submit'>Submit</div>
    </form>
</div>
{% endblock %}

home_space/templates/home_space/index.html
{% extends "home_space/base.html" %}

{% block content %}
<h2>Welcome</h2>
<p><a href="{% url 'register' %}">Register</a> an account to access features.</p>
{% endblock %}

home_space/templates/home_space/inventory_tile.html
<div class="col-12 col-sm-6 col-md-4 px-0 mb-3">
	<div class='card mx-1'>
		<div class='card-header'>
			<h4><a class="text-dark" href="{% url 'inventory' inv.id %}">{{ inv.name }}</a></h4>
		</div>
		<div id='{{ inv.id }}' class='card-body'>
			<div class='list-group list-group-flush mb-0'>
				<div class='list-group-item'>Items: {{ inv.item_set.all.count }}</div>
				{% if inv.holds_food %}
					<div class='list-group-item'>Food: {{ inv.food_set.all.count }}</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>

home_space/templates/home_space/item.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block title %}{{item}}{% endblock %}
{% block content %}
{% if '/garage_sale/' in request.META.HTTP_REFERER and not request.user.is_authenticated %}
<h4 class="mt-0"><a class="text-dark" href="{{ request.META.HTTP_REFERER }}"><i class="glyphicon glyphicon-arrow-left"></i>Back to Sale</a></h4>
{% elif request.user.is_authenticated and request.user == item.space.space.home.owner or ismember %}
<h5 class="mt-0"><a class="text-dark" href="{% url 'dashboard' %}">{{ item.space.space.home }}</a> / <a class="text-dark" href="{% url 'room' item.space.space.id %}">{{item.space.space}}</a> / <a class="text-dark" href="{% url 'inventory' item.space.id %}">{{ item.space }}</a> / {{item}}</h5>
{% endif %}
<div class="modal" id="popupImage" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <img id="modalImage" src="" width="100%" alt="No Image">
            </div>
        </div>
    </div>
</div>
<div>
    <h2 class="mt-0">{{ item }}</h2>
    {% if request.user.is_authenticated and request.user == item.space.space.home.owner or ismember %}
        <a class="btn btn-dark" href="{% url 'new_item_image' item.id %}">Add Image</a>
        <a href="{% url 'edit_item' item.id %}" class="btn btn-dark">Edit Item</a>
    {% endif %}
    <div><h4>Description</h4>{{ item.info }}</div>
    <hr>
    <div class="d-flex row">
    {% for image in item.itemimage_set.all %}
        <div class="col-12 col-sm-6 col-md-3"><img class="itemimage" data-toggle="modal" data-target="#popupImage" src="{{ image.image.url }}" width="100%" alt="No Image"></div>
    {% endfor %}
    </div>
</div>
<script>
$("img.itemimage").on('click', function() {
    $('img#modalImage').attr('src', $(this).attr('src'));
});
</script>
{% endblock %}

home_space/templates/home_space/item_search_inject.html
{% for item in items %}
<li class="list-group-item mt-2"><a id="add_item" class="text-dark" href="{% url 'add_item' sale.id item.id %}">{{ item }}</a></li>
{% endfor %}

home_space/templates/home_space/new_food.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block content %}
<div>
	<p>e.g. Tomato, Potato, Corn...</p>
	<form action="{% url 'new_food' inventory.id %}" method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		<button name="submit">Add Food</button>
	</form>
</div>
{% endblock %}

home_space/templates/home_space/new_garage_sale.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block title %}New Garage Sale{% endblock %}
{% block content %}
<div>
	<h2>Garage Sale.</h2>
	<p>What shall we call it?</p>
	<form action="{% url 'new_garage_sale' %}" method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		<button name="submit" class='btn btn-dark'>Create Garage Sale</button>
	</form>
</div>
{% endblock %}

home_space/templates/home_space/new_item_image.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block title %}Add Image{% endblock %}
{% block content %}
<div>
	<h2 class="mt-0">New Item Image</h2>
	<form action="{% url 'new_item_image' item.id %}" method='post' enctype="multipart/form-data">
		{% csrf_token %}
		{% bootstrap_form form %}
		<button name="submit" class='btn btn-dark'>Add Image</button>
	</form>
</div>
{% endblock %}

home_space/templates/home_space/new_recipe.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block title %}New Recipe{% endblock %}
{% block content %}
<h2>New Recipe</h2>
<div>
	<form action="{% url 'new_recipe' %}" method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		<button class='btn btn-dark' name="submit">Add Recipe</button>
	</form>
		<form action="{% url 'new_ingredient' %}" method='post'>
		{% csrf_token %}
		{% bootstrap_form i_form %}
		<button class='btn btn-dark' name="submit">Add Ingredient</button>
	</form>
</div>
{% endblock %}

home_space/templates/home_space/room.html
{% extends 'home_space/base.html' %}
{% load bootstrap4 %}
{% block title %}{{ room }}{% endblock %}
{% block content %}
<div class="modal" id="delete_room" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5>Delete Image</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
			Are you sure you want to do this?
			</div>
			<div class="modal-footer">
				<a class="btn btn-dark" href="{% url 'delete_room' room.id %}">Confirm</a>
				<button type="button" class="btn btn-dark" data-dismiss="modal" aria-label="Close">Cancel</button>
			</div>
		</div>
	</div>
</div>
<div>
	<h3 class="mt-0"><a class="text-dark" href="{% url 'dashboard' %}">{{room.home}}</a> / {{ room }}{% if room.inventory_set.first.holds_food %} <i class="glyphicon glyphicon-cutlery"></i>{% endif %}</h3>
	<div>
		<div class="btn-group btn-group-sm">
			<div class="dropdown float-left">
				<a href='' class='dropdown-toggle btn btn-dark btn-sm' id='add_inv' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-briefcase"></i> Add Inventory</a>
				<div class='dropdown-menu p-2' aria-labelledby='add_inv'>
					<form action="{% url 'new_inventory' room.id %}" method='post'>
						{% csrf_token %}
						{% bootstrap_form i_form %}
						<button name="submit" class="btn btn-dark">Add Inventory</button>
					</form>
				</div>
			</div>
			<a class="btn btn-dark" href="{% url 'edit_room' room.id %}"><i class="glyphicon glyphicon-edit"></i> Edit Room</a>
			<a class="btn btn-dark" href="{% url 'new_item' room.inventory_set.first.id %}"><i class="glyphicon glyphicon-plus-sign"></i> Add Item</a>
			{% if room.inventory_set.first.holds_food %}
			<a class="btn btn-dark" href="{% url 'new_food' room.inventory_set.first.id %}"><i class="glyphicon glyphicon-shopping-cart"></i> Add Food</a>
			{% endif %}
			<div class="btn btn-dark" data-toggle="modal" data-target="#delete_room"><i class="glyphicon glyphicon-trash"></i> Delete Room</></div>
		</div>
	</div>
	<hr>
	<div>
		<div class='rooms d-flex row'>
			{% for inv in room.inventory_set.all %}
				{% include 'home_space/inventory_tile.html' %}
			{% empty %}
			<div>There is nothing here</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}